version: '3'
services:
  index-processor:
    build: .
    env_file:
      - .env
    environment:
      DB_CONNECTION_URI: ${DB_CONNECTION_URI}
    volumes:
      - ./config.yaml:/app/config/config.yaml
 
